id: IAEAA5EC2
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T06:56:25+00:00'
last_modified: '2022-06-10T06:35:28.973337+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN471
  title: པཎ་ཆེན་སྐུ་ཕྲེང་རིམ་བྱོན་གྱི་མཛད་རྣམ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    B62C:
      image_group_id: I3CN7136
      title: Volume 1 of paN chen sku phreng rim byon gyi rnam thar/
      total_pages: 338
      order: 1
      base_file: B62C.txt
    27B2:
      image_group_id: I3CN7137
      title: Volume 2 of paN chen sku phreng rim byon gyi rnam thar/
      total_pages: 412
      order: 2
      base_file: 27B2.txt
    '0075':
      image_group_id: I3CN7138
      title: Volume 3 of paN chen sku phreng rim byon gyi rnam thar/
      total_pages: 580
      order: 3
      base_file: 0075.txt
    F695:
      image_group_id: I3CN7139
      title: Volume 4 of paN chen sku phreng rim byon gyi rnam thar/
      total_pages: 444
      order: 4
      base_file: F695.txt
    5C54:
      image_group_id: I3CN7140
      title: Volume 5 of paN chen sku phreng rim byon gyi rnam thar/
      total_pages: 432
      order: 5
      base_file: 5C54.txt
    EA6C:
      image_group_id: I3CN7141
      title: Volume 6 of paN chen sku phreng rim byon gyi rnam thar/
      total_pages: 438
      order: 6
      base_file: EA6C.txt
    A7F5:
      image_group_id: I3CN7142
      title: Volume 7 of paN chen sku phreng rim byon gyi rnam thar/
      total_pages: 479
      order: 7
      base_file: A7F5.txt
    563D:
      image_group_id: I3CN7143
      title: Volume 8 of paN chen sku phreng rim byon gyi rnam thar/
      total_pages: 356
      order: 8
      base_file: 563D.txt
    C984:
      image_group_id: I3CN7144
      title: Volume 9 of paN chen sku phreng rim byon gyi rnam thar/
      total_pages: 370
      order: 9
      base_file: C984.txt
    09AD:
      image_group_id: I3CN7145
      title: Volume 10 of paN chen sku phreng rim byon gyi rnam thar/
      total_pages: 536
      order: 10
      base_file: 09AD.txt
    64C1:
      image_group_id: I3CN7146
      title: Volume 11 of paN chen sku phreng rim byon gyi rnam thar/
      total_pages: 508
      order: 11
      base_file: 64C1.txt
    D7CA:
      image_group_id: I3CN7147
      title: Volume 12 of paN chen sku phreng rim byon gyi rnam thar/
      total_pages: 566
      order: 12
      base_file: D7CA.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
